version: '4'
services:
    mysql:
        image: mysql:8
        container_name: mediscreen_mysql_database
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: "mediscreen"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            -   /var/lib/mysql


    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 27017:27017

        networks:
            testing_net:
                ipv4_address: 172.28.1.3

    patient:
        depends_on:
            - mysql
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mediscreen
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        image: patient_microservice
        container_name: patient_microservice
        networks:
            testing_net:
                ipv4_address: 172.28.1.4
        ports:
            - 8081:8081
#        links:
#            - mysql



    note:
        depends_on:
            - mongodb
        image: note_microservice
        networks:
            testing_net:
                ipv4_address: 172.28.1.5
        container_name: note_microservice
        ports:
            - 8082:8082


    rapport:
        depends_on:
            - note
            - patient
        image: rapport_microservice
        container_name: rapport_microservice
        networks:
            testing_net:
                ipv4_address: 172.28.1.6
        ports:
            - 8083:8083

networks:
    testing_net:
         ipam:
            driver: default
            config:
              -   subnet: 172.28.0.0/16
